frr defaults traditional
hostname isp1
log stdout informational
service integrated-vtysh-config
!
router bgp 65000
 bgp router-id 1.1.1.5
 no bgp ebgp-requires-policy
 neighbor 172.16.0.2 remote-as 65000
 neighbor 172.16.0.2 description isp2-ibgp
 neighbor 172.16.1.2 remote-as 65001
 neighbor 172.16.1.2 description hq-edge
 neighbor 172.16.3.2 remote-as 65002
 neighbor 172.16.3.2 description dc-edge
 neighbor 172.16.5.2 remote-as 65003
 neighbor 172.16.5.2 description br1-edge
 !
 address-family ipv4 unicast
  neighbor 172.16.0.2 next-hop-self
 exit-address-family
!
