frr defaults traditional
hostname br2-edge
log stdout informational
service integrated-vtysh-config
!
ip prefix-list OWN-LAN seq 5 permit 10.4.0.0/24
!
route-map TO-ISP permit 10
 match ip address prefix-list OWN-LAN
!
route-map FROM-ISP-PRIMARY permit 10
 set local-preference 200
!
route-map FROM-ISP permit 10
!
router bgp 65004
 bgp router-id 1.1.1.4
 no bgp ebgp-requires-policy
 neighbor 172.16.6.1 remote-as 65000
 neighbor 172.16.6.1 description isp2
 !
 address-family ipv4 unicast
  network 10.4.0.0/24
  neighbor 172.16.6.1 route-map FROM-ISP in
  neighbor 172.16.6.1 route-map TO-ISP out
 exit-address-family
!
