frr defaults traditional
hostname isp2
log stdout informational
service integrated-vtysh-config
!
router bgp 65000
 bgp router-id 1.1.1.6
 no bgp ebgp-requires-policy
 neighbor 172.16.0.1 remote-as 65000
 neighbor 172.16.0.1 description isp1-ibgp
 neighbor 172.16.2.2 remote-as 65001
 neighbor 172.16.2.2 description hq-edge
 neighbor 172.16.4.2 remote-as 65002
 neighbor 172.16.4.2 description dc-edge
 neighbor 172.16.6.2 remote-as 65004
 neighbor 172.16.6.2 description br2-edge
 !
 address-family ipv4 unicast
  neighbor 172.16.0.1 next-hop-self
 exit-address-family
!
